step 2 failure

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,15 +7,18 @@ jobs:
         steps:
             - name: Step 1
               run: sleep 20
+            - name: Fails
+              id: step-2
+              run: exit 1
             - name: Runs on Failure
-              if: failure()
-              run: echo 'Runs only on failure'
+              if: failure() && steps.step-2.conclusion == 'failure'
+              run: echo 'Runs only on failure of step 2'
             - name: Runs on Success
               run: echo 'Runs on Success'
             - name: Always runs
               if: always()
               run: echo 'Always Runs'
-            - name: Runs when calncelled
+            - name: Runs when cancelled
               if: cancelled()
               run: echo 'Runs on cancelled'
     job-2:
